name: fuck_the_sp500
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.2.0+1
  glassmorphism: ^3.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
